### ISSUE TITLE
Crash when I activate

### ISSUE THREAD

**Issue by lindsay-jpg** [MichaelHillcox/XRay-Mod#137]
I was on a multiplayer server simplyvanilla.co and when I tried to activate the mod the game crashed. I copied the crash report if it is needed, I re-downloaded the mod, I uninstalled and then reinstalled forge but to no avail.

Here is the crash report,
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/12/20 4:02 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.client.event.RenderGameOverlayEvent.getMatrixStack()Lcom/mojang/blaze3d/matrix/MatrixStack;
	at com.xray.gui.GuiOverlay.RenderGameOverlayEvent(GuiOverlay.java:31) ~[?:2.3.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_10_GuiOverlay_RenderGameOverlayEvent_RenderGameOverlayEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:634) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:187) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:461) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:950) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:581) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.7.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$409/472234151.call(Unknown Source) [forge-1.16.1-32.0.7.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.xray.gui.GuiOverlay.RenderGameOverlayEvent(GuiOverlay.java:31)
	at net.minecraftforge.eventbus.ASMEventHandler_10_GuiOverlay_RenderGameOverlayEvent_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:634)
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:187)

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['lindsay_jpg'/1898867, l='ClientLevel', x=-45.10, y=73.00, z=5.79], RemoteClientPlayerEntity['blearpandora'/1862403, l='ClientLevel', x=-34.38, y=88.00, z=-3.16]]
	Chunk stats: Client Chunk Cache: 529, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (331,55,224), Chunk: (at 11,3,0 in 20,14; contains blocks 320,0,224 to 335,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 102407 game time, 19001949 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:445)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1976)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:602)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$409/472234151.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1566914272 bytes (1494 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.7.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.7.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.7.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.7.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.16.1-32.0.7.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.7
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.7-client.jar Minecraft {minecraft@1.16.1 DONE}
		forge-1.16.1-32.0.7-universal.jar Forge {forge@32.0.7 DONE}
		xray-1.16.1-2.3.0.jar Advanced XRay {xray@2.3.0 DONE}
	Launched Version: 1.16.1-forge-32.0.7
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 630 GL version 4.5.0 - Build 25.20.100.6617, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

**Comment by MichaelHillcox** [comment]
Update forge and let me know if it's still happening

**Comment by lindsay-jpg** [comment]
I deleted forge and the mod and then updated forge and that worked thank you

**Comment by MichaelHillcox** [comment]
Awesome to hear :+1:
