### ISSUE TITLE
Crashes in 1.11.2

### ISSUE THREAD

**Issue by mackybean** [MichaelHillcox/XRay-Mod#2]
here's a crash log:

```

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 2/6/17 10:59 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fgt X-Ray (fgtxray)
Caused by: java.lang.ClassNotFoundException: com.fgtxray.FgtXRay
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:546)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:563)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:229)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 191769928 bytes (182 MB) / 354922496 bytes (338 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2222 Optifine OptiFine_1.11.2_HD_U_B6 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2222.jar) 
	UC	forge{13.20.0.2222} [Minecraft Forge] (forge-1.11.2-13.20.0.2222.jar) 
	UC	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UC	betterachievements{0.4.1.44} [Better Achievements] (BetterAchievements-1.11.2-0.4.1.44.jar) 
	UC	chestshop-helper{0.0.1} [ChestShop Helper] (ChestShop-1.11.2-0.0.1.jar) 
	UC	selimcore{0.0.2} [Selim's Core] (ChestShop-1.11.2-0.0.1.jar) 
	UC	cosmeticarmorreworked{1.11.2-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1.jar) 
	UC	craftingtweaks{7.1.1} [Crafting Tweaks] (CraftingTweaks_1.11-7.1.1.jar) 
	UC	examplemod{1.0} [examplemod] (fgtxray-1.11.2-1.1.0.1.jar) 
	UE	fgtxray{1.1.0} [Fgt X-Ray] (fgtxray-1.11.2-1.1.0.1.jar) 
	UC	inventorytweaks{1.62-dev-75-f4ba194} [Inventory Tweaks] (InventoryTweaks-1.62-dev-75.jar) 
	UC	jei{4.2.3.223} [Just Enough Items] (jei_1.11.2-4.2.3.223.jar) 
	UC	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UC	minemenu{1.5.0} [MineMenu] (MineMenu-1.11.2-1.5.0-universal.jar) 
	UC	mousetweaks{2.7} [Mouse Tweaks] (MouseTweaks-2.7-mc1.11.2.jar) 
	UC	qualityorder{0.11} [Quality Order] (QualityOrder(0.11)-1.11.2.jar) 
	UC	autoswitch{1.0} [autoswitch] (simpleautoswitch-1.4.jar) 
	UC	simpleautoswitch{1.0} [simpleautoswitch] (simpleautoswitch-1.4.jar) 
	UC	simplyhaxentitydump{1.11} [Simply Hax Entity Dump] (SimplyHax-1.11.2.jar) 
	UC	simplyhaxflying{1.11} [Simply Hax Flying] (SimplyHax-1.11.2.jar) 
	UC	torchpl{1.0} [Torchplacer] (Torchplacer 1.11.2 v1.0.jar) 
	UC	visiblearmorslots{3.0} [Visible Armor Slots] (VisibleArmorSlots[1.11.2]-3.0.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  invtweaks.forge.asm.ContainerTransformer
	OptiFine Version: OptiFine_1.11.2_HD_U_B6
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1.0 - Build 8.15.10.2869
	OpenGlRenderer: Intel(R) 4 Series Internal Chipset
	OpenGlVendor: Intel
	CpuCount: 2

```

**Comment by MichaelHillcox** [comment]
@mackybean Really sorry about this one. I released a fucked version. You can find the fixed version here: https://github.com/MichaelHillcox/XRay-Mod/releases/tag/1.11.2-v1.1.0 and https://mods.curse.com/mc-mods/minecraft/256256-advanced-xray#t1:other-downloads
