### ISSUE TITLE
Crash in 1.11.2

### ISSUE THREAD

**Issue by BobbyWibowo** [MichaelHillcox/XRay-Mod#23]
I used this version: https://github.com/MichaelHillcox/XRay-Mod/tree/1.11.2-v1.3.1 (since I assumed the latest version wouldn't work with 1.11.2).

Crash logs:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.2.0.jar)
  LoadingPlugin (TickDynamic-1.11.2-1.0.0.jar)
  LibrarianLib Plugin (librarianlib-3.1.5.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  LoadingPlugin (Quark-r1.2-93.jar)
  TransformerLoader (OpenComputers-MC1.11.2-1.7.0.40.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  AstralCore (astralsorcery-1.4.5.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.6.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.6.0.jar)
  CTMCorePlugin (CTM-MC1.11.2-0.2.0.8.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.7.15-universal.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  BlurPlugin (Blur-1.0.3-13.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 8/5/17 6:56 AM
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.util.NonNullList.get(SourceFile:40)
	at com.xray.client.gui.GuiList.func_73863_a(GuiList.java:147)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Reflector.callVoid(Reflector.java:547)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1433)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.util.NonNullList.get(SourceFile:40)
	at com.xray.client.gui.GuiList.func_73863_a(GuiList.java:147)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Reflector.callVoid(Reflector.java:547)

-- Screen render details --
Details:
	Screen name: com.xray.client.gui.GuiList
	Mouse location: Scaled: (480, 254). Absolute: (960, 507)
	Screen size: Scaled: (960, 508). Absolute: (1920, 1015). Scale factor of 2
```
The crash would only happen whenever I tried to open the GUI to configure enabled/disabled blocks. I had the key bound to `F4`, which the Controls menu said didn't clash with any other mods. This is a fresh install with a particular modpack on an Ubuntu machine. Previously, the same modpack + this mod worked properly in Windows with the same bound key. So maybe this issue is exclusive in Linux or maybe I missed something this time when installing the modpack? I'm not sure.

The XRay itself worked, though for some reason the first time I turned it on before configuring the blocks list, it showed chests with purple color. Usually in Windows it'd only enable Uranium Ore by default. Don't know if that matters though.

**Comment by MichaelHillcox** [comment]
Well that looks like a fun error. I'll get it sorted :)

**Comment by MichaelHillcox** [comment]
I've release the a hopeful fix for this. 1.12-v1.3.3
