### ISSUE TITLE
Another crash in 1.11.2

### ISSUE THREAD

**Issue by BobbyWibowo** [MichaelHillcox/XRay-Mod#25]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.2.0.jar)
  LoadingPlugin (TickDynamic-1.11.2-1.0.0.jar)
  LibrarianLib Plugin (librarianlib-3.1.5.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  LoadingPlugin (Quark-r1.2-93.jar)
  TransformerLoader (OpenComputers-MC1.11.2-1.7.0.40.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  AstralCore (astralsorcery-1.4.5.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.6.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.6.0.jar)
  CTMCorePlugin (CTM-MC1.11.2-0.2.0.8.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  LoadingPlugin (HardcoreDarkness-MC1.11.2-1.9.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.7.15-universal.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  BlurPlugin (Blur-1.0.3-13.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 8/6/17 12:22 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.util.NonNullList.get(SourceFile:40)
	at com.xray.client.gui.GuiEditOre.<init>(GuiEditOre.java:30)
	at com.xray.client.gui.GuiList.func_73864_a(GuiList.java:129)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.util.NonNullList.get(SourceFile:40)
	at com.xray.client.gui.GuiEditOre.<init>(GuiEditOre.java:30)
	at com.xray.client.gui.GuiList.func_73864_a(GuiList.java:129)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)

-- Affected screen --
Details:
	Screen name: ~~ERROR~~ NullPointerException: null
```
This time it happened when I was trying to edit an ore from the list (right-clicking them). Although it only happened to blocks that, for some reason, ended up not having icons, such as this (Floating Crystal):
![screenshot_20170806_123252](https://user-images.githubusercontent.com/9364930/29000865-95a67e0c-7aa3-11e7-90a2-fda0985a88f1.png)
Previously I got the crash with Destabilized Redstone Ore, though before it happened I went to re-add Destabilized Redstone Ore because of the missing icon. After I re-added it, I attempted to delete the one with missing icon by trying to edit it (right-clicking), which ended up crashing Minecraft instead. That screenshot was taken after I relaunched Minecraft, and for some reason the one with missing icon disappeared from the list as well.
I have no idea why they got their icon missing in the first place though. I didn't make any changes with the mods and all that. Well, I added the blocks in SP and tried to delete in MP, so maybe that was the cause? I don't know.

**Comment by BobbyWibowo** [comment]
I think adding the blocks from SP then using them in MP was the root cause?
Take Destabilized Redstone in the list as an example. Originally I added the liquid form of Destabilized Redstone in SP but it ended up becoming some stairs thing in MP. The same also happened to another ore added by mods in page 2 of the list (a mod's quartz ore becoming some planks thingy).
So it seems blocks added by SP have different IDs in MP or something?

**Comment by MichaelHillcox** [comment]
Well that was stupid of me. I forgot I have the same bit of code in two places.

**Comment by MichaelHillcox** [comment]
Should help some what although from what I can tell its more of a blocks meta issue with the nonNull listing methods. I've done my best. If worst comes to worse then I'll simply remove the previews. Although they are pretty.

**Comment by MichaelHillcox** [comment]
Fixed as of here
https://github.com/MichaelHillcox/XRay-Mod/releases/tag/1.11.2-v1.3.3
